version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    networks:  
      - default
    ports:
      - "8888:8888" # jupyterのdefault port
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - "./app:/opt/app" # 画像やモデルの保存先にはこのディレクトリを使用します

networks:
  default:
